name = "Vanilla Cafe"
author = "root"
version = "0.3.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6dee3e582987047e8b42ed16024d646485fa6681eb8b8c93beccb8fa45f59337"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
