name = "Vanilla Cafe"
author = "root"
version = "0.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "34fa33798ee24b5bc9f8837d75edf3ec871b171b88071867c5945a789c00fb8d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
